### ISSUE TITLE
Always Update Google Play Store Per Release

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [FriendlyNeighborhoodShane/MinMicroG_releases#12]
^ **Update Google Play Store (New Version) Every MinMicroG Releases.** ^

**Comment by FriendlyNeighborhoodShane** [comment]
MinMicroG doesn't use 'Play Store', to be precise.
It uses a [patched version of it](https://gitlab.com/Nanolx/microg-phonesky-iap-support) by Nanolx that enables microG users to make In-App-Purchases, that they wouldn't be able to do with vanilla playstore. Unfortunately, the modded playstore hasnlt been updated in over a year.

I recently tried an experiment to patch a newer playstore version myself that you can find here:
https://github.com/FriendlyNeighborhoodShane/microg-phonesky-iap-support/releases/tag/28.8.18-21
And experimental minmicrog builds with it here:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.01.24

People who've tried it (including me) have experienced crashes with it, but feel free to play with those yourself.

I haven't gotten a good chance to look at the crashes yet, but the problem seems to be in APKtool and how it's secompiling/recompiling the APK.

**Comment by BinariGuy** [comment]
Cant install or update the .apk, guess thats not normal i think

**Comment by FriendlyNeighborhoodShane** [comment]
Yes, the new apk is signed by my keys and it can't update over nanolx's patched playstore. You can replace it in your system partition (or magisk module) manually, or just flash the linked minmicrog zips.

**Comment by chiranz135** [comment]
So replacing the playstore signed with your keys with the latest one is causing bootloop. any fix for that?

**Comment by FriendlyNeighborhoodShane** [comment]
I can't say anything without a logcat from the bootloop, but I can guess it probably doesn't come with all the new privileged-permissions whitelisted for A12.

If you see errors like this in your bootloop logcat:
```
System : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.vending (/system/priv-app/PatchPhonesky): android.permission.XXX}
```
You can just add the relevant permissions (in this example, `android.permission.XXX`) to `/system/etc/permissions/com.android.vending.xml` inside the zip, recompress, and flash.

**Comment by FriendlyNeighborhoodShane** [comment]
This build uses an up-to-date (30.4.21) vanilla (unpatched, self-updating) playstore:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2023.07.29

Will make a release soon.
