### ISSUE TITLE
Some questions regarding MinMicroG

### ISSUE THREAD

**Issue by k2helix** [FriendlyNeighborhoodShane/MinMicroG_releases#22]
Hello, I've been using MinMicroG minimal for months but I want to change to a version with UNLP backends as installing them manually makes location work only sometimes and I hope that if I install it through the package it will work fine (it was working fine with gapps).

My questions are:
- What are the three things in the standard edition that come from OpenGapps used for?
- Is there a way to customize what the package installs? For example, I want something like Minimal but with the UNLP backends and without AuroraServices/Droid like Standard has. Is this possible somehow? (I thought of deleting the files related to them in the zip, but I'm asking as I'm not sure)
- Can I flash another MinMicroG edition over the currently installed?

That's all I'm wondering, thank you for this amazing project!

**Comment by FriendlyNeighborhoodShane** [comment]
- Every component is listed in the main readme: https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/README.md
- Not really, not properly yet. There is code for doing something like this, but it's not 'advertised' as a feature because I personally consider it terrible UX. I'm considering a restructuring of the packages that would solve part of this problem: https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/32#issuecomment-1135798235
  Well, trimming the larger packages by deleting files from them is something I've heard users do use as a form of chainsaw-customisation, and it seems to work for them, but obviously you need to know what to remove, and how to solve any issues you may have because of those changes.
- Yes, but all of them are mutually exclusive so the newer one will just replace the first one.

**Comment by k2helix** [comment]
Hello, thank you for your answer.

1) I know that it is noted in the README, but what do they exactly do?

2) I see, so I should just remove the apks and xml files from packages I don't want to install, right?

3) I see, I thought it wasn't because flashing MinimalIAP over Minimal causes a bootloop (should I open another issue for this?)

**Comment by FriendlyNeighborhoodShane** [comment]
- Swype libs allow swype typing with the default AOSP keyboard (assuming that it's compatible), the DRM jars presumably allow watching DRM-protected content (e.g. in netflix), and the sync adapters automatically sync your contacts and calendard with your google account.
- Pretty much, yeah.
- Well, it's not recommended to switch packages out like themes, because android doesn't deal with constantly changing system packages very well and will start giving you weird problems.
  But it shouldn't cause a bootloop. That could probably be because you're on A12 and using the latest stable release. A bootloop issue was fixed after that but I haven't made a stable release with it yet. Here's the CI builds: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases

**Comment by k2helix** [comment]
Hello again, and thank you for your precise answer.

I edited a bit the MinimalIAP package from the release you provided (added the UNLP backends and edited the defconf file) and now it works flawlessly.
However, I can't seem to get Play Store to work, it says "You're offline. Check your connection or get a notification when you're back online", although I'm certainly connected to my WiFi or cell data. Do you have any idea on what could be causing it?

**Comment by FriendlyNeighborhoodShane** [comment]
Probably a google domain firewalled on your network? Or for some reason the internet permission is denied to play?

**Comment by k2helix** [comment]
Well tbh I don't need the play store, with it yasnac does not pass safetynet, while it works fine on Minimal. I'll let you know if it was caused by an adblock or that permission.

Thanks for your help!
