### ISSUE TITLE
Outdated microG APK's on latest release

### ISSUE THREAD

**Issue by fragtion** [FriendlyNeighborhoodShane/MinMicroG_releases#32]
Thanks for creating this package

However, please post a new release with updated microG APK's? :)

I didn't realize these were out of date and have been struggling for days with microG services core crashing when applying safetynet patch.. problems went away when I installed official apk's from https://github.com/microg/GmsCore/releases

**Comment by FriendlyNeighborhoodShane** [comment]
Hello,

Yeah, I unfortunately haven't had a lot of time to dedicate to the maintainance of this project, due to being busy. I've been wanting to make a stable release for a while now.

In the meanwhile I've set up an automatic build script to make releases whenever something is updated:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/
